apiVersion: batch/v1
kind: Job
metadata:
  name: shiftex-experiment
  namespace: uci-dsm
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: shiftex
          image: nayaksv/shiftex:latest
          imagePullPolicy: Always
          command: ["/bin/bash", "launch.sh"]
          env:
            - name: SERVER_ADDRESS
              value: "localhost:50051"
            - name: EXPECTED_CLIENTS
              value: "4"
            - name: ASSIGNMENT_SEED
              value: "0"
            - name: SEVERITY
              value: "5"
            - name: DATASET
              value: "cifar10c"
          resources:
            limits:
              nvidia.com/gpu: "4"
              cpu: "9"
              memory: "40Gi"
            requests:
              nvidia.com/gpu: "4"
              cpu: "9"
              memory: "40Gi"