# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import expert_matching_pb2 as expert__matching__pb2


class ExpertMatchingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterExpert = channel.unary_unary(
                '/shiftex.ExpertMatchingService/RegisterExpert',
                request_serializer=expert__matching__pb2.ExpertRegistrationRequest.SerializeToString,
                response_deserializer=expert__matching__pb2.ExpertRegistrationResponse.FromString,
                )
        self.AssignTestData = channel.unary_unary(
                '/shiftex.ExpertMatchingService/AssignTestData',
                request_serializer=expert__matching__pb2.TestDataRequest.SerializeToString,
                response_deserializer=expert__matching__pb2.TestDataResponse.FromString,
                )
        self.MatchExpert = channel.unary_unary(
                '/shiftex.ExpertMatchingService/MatchExpert',
                request_serializer=expert__matching__pb2.ExpertMatchRequest.SerializeToString,
                response_deserializer=expert__matching__pb2.ExpertMatchResponse.FromString,
                )
        self.DownloadExpertModel = channel.unary_unary(
                '/shiftex.ExpertMatchingService/DownloadExpertModel',
                request_serializer=expert__matching__pb2.ModelDownloadRequest.SerializeToString,
                response_deserializer=expert__matching__pb2.ModelDownloadResponse.FromString,
                )
        self.ListExperts = channel.unary_unary(
                '/shiftex.ExpertMatchingService/ListExperts',
                request_serializer=expert__matching__pb2.ListExpertsRequest.SerializeToString,
                response_deserializer=expert__matching__pb2.ListExpertsResponse.FromString,
                )
        self.ReportResult = channel.unary_unary(
                '/shiftex.ExpertMatchingService/ReportResult',
                request_serializer=expert__matching__pb2.ResultRequest.SerializeToString,
                response_deserializer=expert__matching__pb2.ResultResponse.FromString,
                )


class ExpertMatchingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterExpert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignTestData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MatchExpert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadExpertModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListExperts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExpertMatchingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterExpert': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterExpert,
                    request_deserializer=expert__matching__pb2.ExpertRegistrationRequest.FromString,
                    response_serializer=expert__matching__pb2.ExpertRegistrationResponse.SerializeToString,
            ),
            'AssignTestData': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignTestData,
                    request_deserializer=expert__matching__pb2.TestDataRequest.FromString,
                    response_serializer=expert__matching__pb2.TestDataResponse.SerializeToString,
            ),
            'MatchExpert': grpc.unary_unary_rpc_method_handler(
                    servicer.MatchExpert,
                    request_deserializer=expert__matching__pb2.ExpertMatchRequest.FromString,
                    response_serializer=expert__matching__pb2.ExpertMatchResponse.SerializeToString,
            ),
            'DownloadExpertModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadExpertModel,
                    request_deserializer=expert__matching__pb2.ModelDownloadRequest.FromString,
                    response_serializer=expert__matching__pb2.ModelDownloadResponse.SerializeToString,
            ),
            'ListExperts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExperts,
                    request_deserializer=expert__matching__pb2.ListExpertsRequest.FromString,
                    response_serializer=expert__matching__pb2.ListExpertsResponse.SerializeToString,
            ),
            'ReportResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportResult,
                    request_deserializer=expert__matching__pb2.ResultRequest.FromString,
                    response_serializer=expert__matching__pb2.ResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shiftex.ExpertMatchingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExpertMatchingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterExpert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shiftex.ExpertMatchingService/RegisterExpert',
            expert__matching__pb2.ExpertRegistrationRequest.SerializeToString,
            expert__matching__pb2.ExpertRegistrationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AssignTestData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shiftex.ExpertMatchingService/AssignTestData',
            expert__matching__pb2.TestDataRequest.SerializeToString,
            expert__matching__pb2.TestDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MatchExpert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shiftex.ExpertMatchingService/MatchExpert',
            expert__matching__pb2.ExpertMatchRequest.SerializeToString,
            expert__matching__pb2.ExpertMatchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadExpertModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shiftex.ExpertMatchingService/DownloadExpertModel',
            expert__matching__pb2.ModelDownloadRequest.SerializeToString,
            expert__matching__pb2.ModelDownloadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListExperts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shiftex.ExpertMatchingService/ListExperts',
            expert__matching__pb2.ListExpertsRequest.SerializeToString,
            expert__matching__pb2.ListExpertsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shiftex.ExpertMatchingService/ReportResult',
            expert__matching__pb2.ResultRequest.SerializeToString,
            expert__matching__pb2.ResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
