# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import expert_matching_pb2 as proto_dot_expert__matching__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/expert_matching_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExpertMatchingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterExpert = channel.unary_unary(
                '/shiftex.ExpertMatchingService/RegisterExpert',
                request_serializer=proto_dot_expert__matching__pb2.ExpertRegistrationRequest.SerializeToString,
                response_deserializer=proto_dot_expert__matching__pb2.ExpertRegistrationResponse.FromString,
                _registered_method=True)
        self.AssignTestData = channel.unary_unary(
                '/shiftex.ExpertMatchingService/AssignTestData',
                request_serializer=proto_dot_expert__matching__pb2.TestDataRequest.SerializeToString,
                response_deserializer=proto_dot_expert__matching__pb2.TestDataResponse.FromString,
                _registered_method=True)
        self.MatchExpert = channel.unary_unary(
                '/shiftex.ExpertMatchingService/MatchExpert',
                request_serializer=proto_dot_expert__matching__pb2.ExpertMatchRequest.SerializeToString,
                response_deserializer=proto_dot_expert__matching__pb2.ExpertMatchResponse.FromString,
                _registered_method=True)
        self.DownloadExpertModel = channel.unary_unary(
                '/shiftex.ExpertMatchingService/DownloadExpertModel',
                request_serializer=proto_dot_expert__matching__pb2.ModelDownloadRequest.SerializeToString,
                response_deserializer=proto_dot_expert__matching__pb2.ModelDownloadResponse.FromString,
                _registered_method=True)
        self.ListExperts = channel.unary_unary(
                '/shiftex.ExpertMatchingService/ListExperts',
                request_serializer=proto_dot_expert__matching__pb2.ListExpertsRequest.SerializeToString,
                response_deserializer=proto_dot_expert__matching__pb2.ListExpertsResponse.FromString,
                _registered_method=True)
        self.ReportResult = channel.unary_unary(
                '/shiftex.ExpertMatchingService/ReportResult',
                request_serializer=proto_dot_expert__matching__pb2.ResultRequest.SerializeToString,
                response_deserializer=proto_dot_expert__matching__pb2.ResultResponse.FromString,
                _registered_method=True)


class ExpertMatchingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterExpert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignTestData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MatchExpert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadExpertModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListExperts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExpertMatchingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterExpert': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterExpert,
                    request_deserializer=proto_dot_expert__matching__pb2.ExpertRegistrationRequest.FromString,
                    response_serializer=proto_dot_expert__matching__pb2.ExpertRegistrationResponse.SerializeToString,
            ),
            'AssignTestData': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignTestData,
                    request_deserializer=proto_dot_expert__matching__pb2.TestDataRequest.FromString,
                    response_serializer=proto_dot_expert__matching__pb2.TestDataResponse.SerializeToString,
            ),
            'MatchExpert': grpc.unary_unary_rpc_method_handler(
                    servicer.MatchExpert,
                    request_deserializer=proto_dot_expert__matching__pb2.ExpertMatchRequest.FromString,
                    response_serializer=proto_dot_expert__matching__pb2.ExpertMatchResponse.SerializeToString,
            ),
            'DownloadExpertModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadExpertModel,
                    request_deserializer=proto_dot_expert__matching__pb2.ModelDownloadRequest.FromString,
                    response_serializer=proto_dot_expert__matching__pb2.ModelDownloadResponse.SerializeToString,
            ),
            'ListExperts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExperts,
                    request_deserializer=proto_dot_expert__matching__pb2.ListExpertsRequest.FromString,
                    response_serializer=proto_dot_expert__matching__pb2.ListExpertsResponse.SerializeToString,
            ),
            'ReportResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportResult,
                    request_deserializer=proto_dot_expert__matching__pb2.ResultRequest.FromString,
                    response_serializer=proto_dot_expert__matching__pb2.ResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shiftex.ExpertMatchingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shiftex.ExpertMatchingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExpertMatchingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterExpert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shiftex.ExpertMatchingService/RegisterExpert',
            proto_dot_expert__matching__pb2.ExpertRegistrationRequest.SerializeToString,
            proto_dot_expert__matching__pb2.ExpertRegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignTestData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shiftex.ExpertMatchingService/AssignTestData',
            proto_dot_expert__matching__pb2.TestDataRequest.SerializeToString,
            proto_dot_expert__matching__pb2.TestDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MatchExpert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shiftex.ExpertMatchingService/MatchExpert',
            proto_dot_expert__matching__pb2.ExpertMatchRequest.SerializeToString,
            proto_dot_expert__matching__pb2.ExpertMatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadExpertModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shiftex.ExpertMatchingService/DownloadExpertModel',
            proto_dot_expert__matching__pb2.ModelDownloadRequest.SerializeToString,
            proto_dot_expert__matching__pb2.ModelDownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListExperts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shiftex.ExpertMatchingService/ListExperts',
            proto_dot_expert__matching__pb2.ListExpertsRequest.SerializeToString,
            proto_dot_expert__matching__pb2.ListExpertsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shiftex.ExpertMatchingService/ReportResult',
            proto_dot_expert__matching__pb2.ResultRequest.SerializeToString,
            proto_dot_expert__matching__pb2.ResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
